const fs = require('fs')
const path = require('path')
const srcFolder = path.join(__dirname, 'src', 'blocks')
const outFolder = path.join(__dirname, 'out')
fs.rmdirSync(outFolder, {recursive: true})
fs.mkdirSync(outFolder, {recursive: true})
fs.rmdirSync(srcFolder, {recursive: true})
fs.mkdirSync(srcFolder, {recursive: true})
require('./fill_files.js')
require('./make_canvas.js')